# Generated by Django 3.2 on 2024-03-06 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('resolution_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"tickets_details"',
            },
        ),
    ]
