# Generated by Django 3.2 on 2024-03-06 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"tickets_employee"',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_leave', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.employee')),
            ],
            options={
                'db_table': '"tickets_duty_roster"',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.employee'),
        ),
    ]
