# Generated by Django 3.2 on 2024-03-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20240306_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
